---
title: "BRUV Data 2019"
author: "Jessica Madden"
date: "December 17, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(here)
library(tidyverse)
library(kableExtra)
library(janitor)
library(data.table)
library(knitr)
library(wesanderson)

```

```{r}
# Load in data
max_n_data <- read.csv(here("data", "max_n_data.csv")) %>% 
  clean_names() %>% 
  rename("family" = "family_x") %>% 
  arrange(geog, date, bruv, common)

max_n_complete <- max_n_data %>% 
  select(op_code, site_full, type, geog, date, bruv, subclass, family, common, max_n) %>% 
  complete(nesting(op_code, site_full, type, geog, date, bruv), nesting(subclass, family, common), fill=list(number=0)) %>% 
  group_by(op_code, site_full, type, geog, date, bruv, subclass, family, common) %>% 
  summarize(max_n = sum(max_n)) %>% 
  arrange(geog, date, bruv, common)

# Change NA to zeros

max_n_complete$max_n[is.na(max_n_complete$max_n)] = 0

# Add a column for pairs so I can group them

max_n_complete <- max_n_complete %>% 
  mutate(pair = case_when(
    site_full %in% c("Percos", "Refugio") ~ "PC", 
    site_full %in% c("Haskells", "South Campus") ~ "SB", 
    site_full %in% c("Leo Carrillo", "Dume Cove") ~ "LA", 
    site_full %in% c("Sleepy Hollow", "Strands") ~ "OC", 
    site_full %in% c("San Elijo", "Scripps") ~ "SD"
  ))


```

### MaxN: MPA Status

```{r}
# Mean MaxN MPA vs. Reference

mpa_ref <- max_n_data %>% 
  group_by(op_code, type) %>% 
  summarize(maxn_sum = sum(max_n)) %>% 
  group_by(type) %>% 
  summarize(
    mean_maxn = mean(maxn_sum), 
    se = sd(maxn_sum)/(sqrt(n()))
  )
  
```

```{r, fig.align='center', fig.width=10, fig.cap="**Figure 1.** MAxN comparison between MPA and Reference sites. The MAxN for each species was summed for each BRUV video, then this total MAxN was averaged across all BRUV deployments for MPA sites (n = 45) and Reference sites (n = 45)."}
ggplot(mpa_ref, aes(x = type, y = mean_maxn, fill = type)) +
  geom_bar(stat="identity", 
           color = "black", 
           size = 0.25)  +
  scale_fill_manual(values = wes_palette("Moonrise2")) +
  geom_errorbar(aes(x = type, ymax = mean_maxn + se, ymin = mean_maxn - se), 
                width = .05, 
                alpha = 0.9, 
                position = position_dodge(width = 10)) +
  theme_minimal() +
  theme(axis.line.x = element_line(size=0.25),
        axis.line.y = element_line(size=0.25),
        axis.text.x = element_text(size=10, color="black", vjust=0.3),
        axis.text.y = element_text(size=10, color="black"),
        axis.ticks=element_line(color="black", size=0.25),
        axis.title.x = element_text(size = 10, color = "black"),
        legend.position="none",
        panel.background=element_blank(),
        panel.grid=element_blank()) +
  scale_y_continuous(expand = c(0, 0), 
                     limits = c(0, 50)) +
  labs(x = "", y = "Mean MaxN Total per BRUV (+/- SE)")
```

```{r}
mean_maxn_sites <- max_n_complete %>% 
  group_by(op_code, site_full, geog, type, pair) %>% 
  summarize(maxn_sum = sum(max_n)) %>% 
  group_by(site_full, geog, type, pair) %>% 
  summarize(
    mean_maxn = mean(maxn_sum), 
    se = sd(maxn_sum)/(sqrt(n()))
  ) %>% 
  arrange(geog)
  
```

```{r, fig.align='center', fig.width=10, fig.cap=""}
ggplot(mean_maxn_sites, aes(x = pair, y = mean_maxn, fill = type)) +
  geom_bar(stat="identity", 
           position = "dodge",
           color = "black", 
           size = 0.25)  +
  scale_fill_manual(values = wes_palette("Moonrise2")) +
  geom_errorbar(aes(x = pair, ymax = mean_maxn + se, ymin = mean_maxn - se), 
                width = .1, 
                position = position_dodge(1)) +
  theme_minimal() +
  theme(axis.line.x = element_line(size=0.25),
        axis.line.y = element_line(size=0.25),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size=10, color="black"),
        axis.ticks=element_line(color="black", size=0.25),
        axis.title.x = element_text(size = 10, color = "black"),
        legend.position="none",
        panel.background=element_blank(),
        panel.grid=element_blank()) +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "", y = "Mean Total MaxN per BRUV (+/- SE)") +
  scale_x_discrete(labels=c())
```

