---
title: "MaxN_data_summary"
author: "Jessica Madden"
date: "November 13, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
```

1. Move all files to merge into working directory
2. Define files as the list of all files in working directory and loop them all into a data frame

```{r}
files <- list.files("C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/max-n/") #Creates a vector of all file names
maxN_data <- data.frame() #Create empty data frame
for (file in files){
  print(file)
  df <- read.delim(paste0("C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/max-n/", file), header = TRUE, sep = "\t", dec = ".", skip = 4)
  maxN_data <- rbind.fill(maxN_data, df)
} #Loops each file filling into data frame
```

3. Clean up the data a bit
```{r}
maxN_cleaned <- maxN_data %>% 
  clean_names()
```

4. Some data wrangling
```{r}
#Use OpCode to fill site, date, and bruv columns

maxN_bruv_data <- maxN_cleaned %>% 
  mutate(site_code = substr(op_code, 1, 4)) %>% 
  mutate(bruv = substr(op_code, 18, 18)) %>% 
  mutate(date = substr(op_code, 6, 12)) %>%  
  mutate(date = dmy(date)) %>%  #Converts date into date format using lubridate package
  mutate(day = day(date)) %>% #Creates column for day
  mutate(month = month(date)) %>%  #Creates column for month
  mutate(year = year(date)) #Creates column for year
  

```

```{r}
#Create a column for common name
common_names <- read.delim("file:///C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/mpa_BRUV_specieslist.txt")
common_names <- clean_names(common_names)

maxN_bruv_data <- maxN_bruv_data %>% 
  mutate(code = substr(code, 1, 2)) %>% #clean up code column to just integer %>% 
  mutate(code = as.integer(code)) %>%  #Convert code to class integer
  full_join(common_names, by = c("code" = "caab_code")) #join common names to data set

#Create column for species code

species_codes <- read.csv(here("data", "MPA_sp_codes_fish.csv")) %>% 
  clean_names() #%>% 
  #separate("scientific_name", c("genus", "species"), sep = " ", remove = FALSE)

maxN_bruv_data <- maxN_bruv_data %>% 
  unite("scientific_name", c("genus.x", "species.x"), sep = " ", remove = FALSE) %>% 
  full_join(species_codes, by = c("common" = "common_name"))
```

```{r}
#Create list of MPA and Reference sites
MPA <- list("WABE", "PERC", "SOCA", "DUCO", "SLHO", "SCRI")
Reference <- list("PISM", "REFU", "HASK", "LECA", "STBE", "SAEL")
site_full <- c("Pismo", "Wall", "Percos", "Refugio", "Haskells", "South Campus", "Leo Carrillo", "Dume Cove", "Sleepy Hollow", "Strands", "San Elijo", "Scripps")

#Filter for just columns of interest for maxN summary
max_n_data <- maxN_bruv_data %>% 
  select(site_code, op_code, date, day, month, year, bruv, subclass, family.x, genus.x, species.x, sp_code, common, max_n) %>% 
  mutate(MPA = ifelse(site_code %in% MPA, 1, 0)) %>% #Adds column where value of 1 means MPA site, 0 is ref
  mutate(site_full = case_when(
    site_code == "WABE" ~ "Wall Beach", 
    site_code == "PISM" ~ "Pismo", 
    site_code == "PERC" ~ "Percos", 
    site_code == "REFU" ~ "Refugio", 
    site_code == "HABE" ~ "Haskells", 
    site_code == "SOCA" ~ "South Campus", 
    site_code == "LECA" ~ "Leo Carrillo", 
    site_code == "DUCO" ~ "Dume Cove", 
    site_code == "SLHO" ~ "Sleepy Hollow", 
    site_code == "STBE" ~ "Strands", 
    site_code == "SAEL" ~ "San Elijo", 
    site_code == "SCRI" ~ "Scripps"
  )) %>% #Adds column with full site name
  drop_na(site_code) %>%  #removes non-data from species list file
    mutate(geog = case_when(
    site_code == "WABE" ~ 1, 
    site_code == "PISM" ~ 2, 
    site_code == "PERC" ~ 3, 
    site_code == "REFU" ~ 4, 
    site_code == "SOCA" ~ 5, 
    site_code == "HABE" ~ 6, 
    site_code == "DUCO" ~ 7, 
    site_code == "LECA" ~ 8, 
    site_code == "SLHO" ~ 9, 
    site_code == "STBE" ~ 10, 
    site_code == "SCRI" ~ 11, 
    site_code == "SAEL" ~ 12
  )) %>% #added geographic sorting column
  mutate(type = case_when(
    MPA == "1" ~ "MPA", 
    MPA == "0" ~ "Reference"
  )) %>%  #adds columns for mpa/reference
  arrange(geog, date, bruv)


#Save to csv

write.csv(max_n_data, "file:///C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data//max_n_data.csv")


```


