---
title: "Point Measurements"
author: "Jessica Madden"
date: "December 15, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)

```

1. Move all files to merge into working directory
2. Define files as the list of all files in working directory and loop them all into a data frame

```{r}
files <- list.files("C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/point-data/") #Creates a vector of all file names
point_data_raw <- data.frame() #Create empty data frame
for (file in files){
  print(file)
  df <- read.delim(paste0("C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/point-data/", file), header = TRUE, sep = "\t", dec = ".", skip = 4)
  point_data_raw <- rbind.fill(point_data_raw, df)
} #Loops each file filling into data frame
```

```{r}
# Some data cleaning and initial wrangling
#Use OpCode to fill site, date, and bruv columns

point_data <- point_data_raw %>% 
  clean_names() %>% 
  mutate(site_code = substr(op_code, 1, 4)) %>% 
  mutate(bruv = substr(op_code, 18, 18)) %>% 
  mutate(date = substr(op_code, 6, 12)) %>%  
  mutate(date = dmy(date)) %>%  #Converts date into date format using lubridate package
  mutate(day = day(date)) %>% #Creates column for day
  mutate(month = month(date)) %>%  #Creates column for month
  mutate(year = year(date)) %>%  #Creates column for year
  select(op_code, site_code, date, day, month, year, bruv, period_time_hms, visibility, habitat, family, genus, species, code, number, comment_1, x_6) %>% 
  mutate(time = hms(period_time_hms)) %>% 
  mutate(minute = minute(time)) %>% 
  mutate(second = second(time))    


```


```{r}
#Create a column for common name
common_names <- read.delim("file:///C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data/mpa_BRUV_specieslist.txt") %>% 
  clean_names()

point_data <- point_data %>% 
  mutate(code = substr(code, 1, 2)) %>% #clean up code column to just integer %>% 
  mutate(code = as.integer(code)) %>%  #Convert code to class integer
  full_join(common_names, by = c("code" = "caab_code"))   #join common names to data set

#Create column for species code

species_codes <- read.csv(here::here("data", "MPA_sp_codes_fish.csv")) %>% 
  clean_names() #%>% 
  #separate("scientific_name", c("genus", "species"), sep = " ", remove = FALSE)

point_data <- point_data %>% 
  unite("scientific_name", c("genus.x", "species.x"), sep = " ", remove = FALSE) %>% 
  full_join(species_codes, by = c("common" = "common_name")) 

#Create list of MPA and Reference sites
MPA <- list("WABE", "PERC", "SOCA", "DUCO", "SLHO", "SCRI")
Reference <- list("PISM", "REFU", "HASK", "LECA", "STBE", "SAEL")
site_full <- c("Pismo", "Wall", "Percos", "Refugio", "Haskells", "South Campus", "Leo Carrillo", "Dume Cove", "Sleepy Hollow", "Strands", "San Elijo", "Scripps")

#Add column for mpa status, full site name and geog

point_data <- point_data %>% 
  mutate(MPA = ifelse(site_code %in% MPA, 1, 0)) %>% #Adds column where value of 1 means MPA site, 0 is ref
  mutate(site_full = case_when(
    site_code == "WABE" ~ "Wall Beach", 
    site_code == "PISM" ~ "Pismo", 
    site_code == "PERC" ~ "Percos", 
    site_code == "REFU" ~ "Refugio", 
    site_code == "HABE" ~ "Haskells", 
    site_code == "SOCA" ~ "South Campus", 
    site_code == "LECA" ~ "Leo Carrillo", 
    site_code == "DUCO" ~ "Dume Cove", 
    site_code == "SLHO" ~ "Sleepy Hollow", 
    site_code == "STBE" ~ "Strands", 
    site_code == "SAEL" ~ "San Elijo", 
    site_code == "SCRI" ~ "Scripps"
  )) %>% #Adds column with full site name
  drop_na(site_code) %>%  #removes non-data from species list file
    mutate(geog = case_when(
    site_code == "WABE" ~ 1, 
    site_code == "PISM" ~ 2, 
    site_code == "PERC" ~ 3, 
    site_code == "REFU" ~ 4, 
    site_code == "SOCA" ~ 5, 
    site_code == "HABE" ~ 6, 
    site_code == "DUCO" ~ 7, 
    site_code == "LECA" ~ 8, 
    site_code == "SLHO" ~ 9, 
    site_code == "STBE" ~ 10, 
    site_code == "SCRI" ~ 11, 
    site_code == "SAEL" ~ 12
  )) %>% #added geographic sorting column
  mutate(type = case_when(
    MPA == "1" ~ "MPA", 
    MPA == "0" ~ "Reference"
  )) %>%  #adds columns for mpa/reference
  arrange(geog, date, bruv) %>%
  select(op_code, site_full, site_code, type, geog, date, day, month, year, bruv, period_time_hms, time, minute, second, visibility, habitat, subclass, family.x, scientific_name.x, genus.x, species.x, common, code, sp_code, number, comment_1, x_6) %>% 
  rename("family" = "family.x", 
         "scientific_name" = "scientific_name.x", 
         "genus" = "genus.x", 
         "species" = "species.x")


```


```{r}
# Checking MAxN of species by site to MaxN output data *****Changing what variables you group by here will discern between them, like background vs foreground and habitat

maxN <- point_data %>% 
  group_by(site_full, common) %>% 
  summarise(
    maxn = max(number)
  ) 
```


```{r}
# Create column with assigned intervals depending on time segment 
# 5 min:

five_min <- ms(c("00:00.00", "05:00.00", "10:00.00", "15:00.00", "20:00.00", "25:00.00", "30:00.00", "35:00.00", "40:00.00", "45:00.00", "50:00.00", "55:00.00", "60:00.00"))

point_data <- point_data %>% 
  mutate(five_min = case_when(
    time >= ms("00:00.00") & time <  ms("05:00.00") ~ 5, 
    time >= ms("05:00.00") & time <  ms("10:00.00") ~ 10, 
    time >= ms("10:00.00") & time <  ms("15:00.00") ~ 15, 
    time >= ms("15:00.00") & time <  ms("20:00.00") ~ 20, 
    time >= ms("20:00.00") & time <  ms("25:00.00") ~ 25, 
    time >= ms("25:00.00") & time <  ms("30:00.00") ~ 30, 
    time >= ms("30:00.00") & time <  ms("35:00.00") ~ 35, 
    time >= ms("35:00.00") & time <  ms("40:00.00") ~ 40, 
    time >= ms("40:00.00") & time <  ms("45:00.00") ~ 45, 
    time >= ms("45:00.00") & time <  ms("50:00.00") ~ 50, 
    time >= ms("50:00.00") & time <  ms("55:00.00") ~ 55, 
    time >= ms("55:00.00") & time <=  ms("60:00.00") ~ 60
  ))
```  

```{r}
# Create column with assigned intervals depending on time segment 
# 10 min:

point_data <- point_data %>% 
  mutate(ten_min = case_when(
    time >= ms("00:00.00") & time <  ms("10:00.00") ~ 10, 
    time >= ms("10:00.00") & time <  ms("20:00.00") ~ 20, 
    time >= ms("20:00.00") & time <  ms("30:00.00") ~ 30, 
    time >= ms("30:00.00") & time <  ms("40:00.00") ~ 40, 
    time >= ms("40:00.00") & time <  ms("50:00.00") ~ 50, 
    time >= ms("50:00.00") & time <=  ms("60:00.00") ~ 60
  ))
 
```

```{r}
#Save to csv

write.csv(point_data, "file:///C:/Users/Crab Lab/Box/Crab Lab Group Folder/MPA Project/mpa_project_code/bruv-data/data//point_data.csv")
```
